// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJH36VEMf22uE4v-xNekr3EO04kmrCapE',
    appId: '1:230870401634:web:db662c6d9596e4d7c3c73b',
    messagingSenderId: '230870401634',
    projectId: 'shopin-379ad',
    authDomain: 'shopin-379ad.firebaseapp.com',
    databaseURL: 'https://shopin-379ad-default-rtdb.firebaseio.com',
    storageBucket: 'shopin-379ad.appspot.com',
    measurementId: 'G-NQHR68ZELX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHbS279TE1vD_P7X6L5ebG4KLtCpV3OR4',
    appId: '1:230870401634:android:f07d752534e70605c3c73b',
    messagingSenderId: '230870401634',
    projectId: 'shopin-379ad',
    databaseURL: 'https://shopin-379ad-default-rtdb.firebaseio.com',
    storageBucket: 'shopin-379ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzysga4DILY4l77k-VeK8n1fGyItbOSPA',
    appId: '1:230870401634:ios:5039b3d7045eca66c3c73b',
    messagingSenderId: '230870401634',
    projectId: 'shopin-379ad',
    databaseURL: 'https://shopin-379ad-default-rtdb.firebaseio.com',
    storageBucket: 'shopin-379ad.appspot.com',
    iosBundleId: 'com.example.shopin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzysga4DILY4l77k-VeK8n1fGyItbOSPA',
    appId: '1:230870401634:ios:b5e6d118943c7ef0c3c73b',
    messagingSenderId: '230870401634',
    projectId: 'shopin-379ad',
    databaseURL: 'https://shopin-379ad-default-rtdb.firebaseio.com',
    storageBucket: 'shopin-379ad.appspot.com',
    iosBundleId: 'com.example.shopin.RunnerTests',
  );
}
